### ISSUE TITLE
Simplify contributing to the project

### ISSUE THREAD

**Issue by jchristgit** [strinking/site#4]
This is (intended as) a community project, but right now it's fairly hard to set up locally. Reasons being:
- statbot is hooked into the app. Users need to have an instance running, which involves setting up PGSQL.
- Some things are hardcoded and that's *bad*. I'm going to look into factoring them out into a module, probably a settings module.
- The whole OAuth setup process is very tedious.

If anyone has ideas on how to improve this, I'd be happy to work on it.

**Comment by aeshthetic** [comment]
🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳 🐳
